---
title: "Reports"
description: |
  Reports are limited to the most recent Malaria Indicator Survey or Demographic and Health Survey for each country. They are available in English and in French. 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Reports

- [Angola](files/Angola_Textile_Report.html)
- [Benin](files/Benin_Textile_Report.html)
- [Burkina Faso](files/Burkina Faso 2022_Textile_Report.html)
- [Burundi](files/Burundi_Textile_Report.html)
- [Cameroon](files/Cameroon_Textile_Report.html)
- [Central African Republic](files/Central African Republic_Textile_Report.html)
- [Chad](files/Chad_Textile_Report.html)
- [Cote d'Ivoire](files/Cote d'Ivoire_Textile_Report.html)
- [DRC](files/DRC_Textile_Report.html)
- [Gambia](files/Gambia_Textile_Report.html)
- [Ghana](files/Ghana_Textile_Report.html)
- [Guinea](files/Guinea_Textile_Report.html)
- [Kenya](files/Kenya_Textile_Report.html)
- [Liberia](files/Liberia_Textile_Report.html)
- [Madagascar](files/Madagascar_Textile_Report.html)
- [Malawi](files/Malawi_Textile_Report.html)
- [Mali](files/Mali_Textile_Report.html)
- [Mauritania](files/Mauritania_Textile_Report.html)
- [Mozambique](files/Mozambique_Textile_Report.html)
- [Nigeria](files/Nigeria_Textile_Report.html)
- [Republic of Congo](files/Republic of Congo_Textile_Report.html)
- [Rwanda](files/Rwanda_Textile_Report.html)
- [Sao Tome & Principe](files/Sao Tome & Principe_Textile_Report.html)
- [Senegal](files/Senegal_Textile_Report.html)
- [Tanzania](files/Tanzania_Textile_Report.html)
- [Togo](files/Togo_Textile_Report.html)
- [Uganda](files/Uganda_Textile_Report.html)
- [Zambia](files/Zambia_Textile_Report.html)
- [Zimbabwe](files/Zimbabwe_Textile_Report.html)

